# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design/password.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import threading

hide_trigger = False
w_width = 400
w_height = 150


class Ui_Password(object):
    def setupUi(self, Password):

        # self.input_pass = input_pass

        Password.setObjectName("Password")
        Password.resize(400, 139)
        self.centralwidget = QtWidgets.QWidget(Password)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 391, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pass_input = QtWidgets.QLineEdit(self.centralwidget)
        self.pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_input.setGeometry(QtCore.QRect(10, 40, 381, 25))
        self.pass_input.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_input.setObjectName("pass_input")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(80, 80, 89, 31))
        self.ok_button.setObjectName("ok_button")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(240, 80, 89, 31))
        self.cancel_button.setObjectName("cancel_button")
        self.hide_unhide_button = QtWidgets.QPushButton(self.centralwidget)
        self.hide_unhide_button.setGeometry(QtCore.QRect(359, 40, 31, 25))
        self.hide_unhide_button.setText("")
        self.hide_unhide_button.setObjectName("hide_unhide_button")

        # icon for button
        self.ok_button.setIcon(QtGui.QIcon('./icon/apply.jpeg'))
        self.cancel_button.setIcon(QtGui.QIcon('./icon/cancel.png'))
        self.hide_unhide_button.setIcon(QtGui.QIcon('./icon/unhide.png'))

        # event button
        self.hide_unhide_button.clicked.connect(self.hide_unhide_pass)


        Password.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Password)
        self.statusbar.setObjectName("statusbar")
        Password.setStatusBar(self.statusbar)
        self.retranslateUi(Password)
        QtCore.QMetaObject.connectSlotsByName(Password)

    def hide_unhide_pass(self):
        global hide_trigger
        hide_trigger = not hide_trigger
        if hide_trigger:
            self.pass_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        else:
            self.pass_input.setEchoMode(QtWidgets.QLineEdit.Password)

    def retranslateUi(self, Password):
        _translate = QtCore.QCoreApplication.translate
        Password.setWindowTitle(_translate("Password", "Password Window"))
        self.label.setText(_translate("Password", "Vui lòng nhập Password !"))


class MainWindow(QtWidgets.QMainWindow, Ui_Password):
    def __init__(self):
        global w_height, w_width
        super().__init__()
        self.setupUi(self)
        self.setFixedSize(w_width, w_height)

    def closeEvent(self, event):
        super().closeEvent(event)

# if __name__ == '__main__':
#     import sys
#
#     app = QtWidgets.QApplication(sys.argv)
#     QtCore.QCoreApplication.setOrganizationName("Eyllanesc")
#     QtCore.QCoreApplication.setOrganizationDomain("eyllanesc.com")
#     QtCore.QCoreApplication.setApplicationName("MyApp")
#     w = MainWindow()
#     w.show()
#     app.exec_()


def password_run():
    import sys

    app = QtWidgets.QApplication(sys.argv)
    QtCore.QCoreApplication.setOrganizationName("Eyllanesc")
    QtCore.QCoreApplication.setOrganizationDomain("eyllanesc.com")
    QtCore.QCoreApplication.setApplicationName("MyApp")
    w = MainWindow()
    w.show()
    app.exec_()


def password_by_threading():
    t = threading.Thread(target = password_run, args = [])
    t.start()


