# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design/test_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

w_width = 900
w_height = 700


def restore(settings):
    finfo = QtCore.QFileInfo(settings.fileName())
    if finfo.exists() and finfo.isFile():
        for w in QtWidgets.qApp.allWidgets():
            mo = w.metaObject()
            if w.objectName() and not w.objectName().startswith("qt_"):
                settings.beginGroup(w.objectName())
                for i in range(mo.propertyCount(), mo.propertyOffset() - 1, -1):
                    prop = mo.property(i)
                    if prop.isWritable():
                        name = prop.name()
                        val = settings.value(name, w.property(name))
                        if str(val).isdigit():
                            val = int(val)
                        w.setProperty(name, val)
                settings.endGroup()


def save(settings):
    for w in QtWidgets.qApp.allWidgets():
        mo = w.metaObject()
        if w.objectName() and not w.objectName().startswith("qt_"):
            settings.beginGroup(w.objectName())
            for i in range(mo.propertyCount()):
                prop = mo.property(i)
                name = prop.name()
                if prop.isWritable():
                    settings.setValue(name, w.property(name))
            settings.endGroup()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(40, 20, 281, 461))
        self.groupBox_5.setObjectName("groupBox_5")
        # self.groupBox_5.show()
        self.table = QtWidgets.QTableWidget(self.groupBox_5)
        self.table.setGeometry(QtCore.QRect(0, 20, 281, 391))
        self.table.setGridStyle(QtCore.Qt.DashDotLine)
        self.table.setRowCount(15)
        self.table.setColumnCount(2)
        self.table.setObjectName("table")
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(1, 1, item)
        self.table.horizontalHeader().setDefaultSectionSize(121)
        self.table.horizontalHeader().setMinimumSectionSize(58)
        self.table.verticalHeader().setDefaultSectionSize(25)
        self.bat_dau = QtWidgets.QPushButton(self.groupBox_5)
        self.bat_dau.setGeometry(QtCore.QRect(10, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bat_dau.setFont(font)
        self.bat_dau.setObjectName("bat_dau")
        self.bat_dau.setIcon(QtGui.QIcon('./pictures/LogoTCX_small.png'))
        self.bat_dau.setFixedSize()
        self.tam_dung = QtWidgets.QPushButton(self.groupBox_5)
        self.tam_dung.setGeometry(QtCore.QRect(110, 420, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tam_dung.setFont(font)
        self.tam_dung.setObjectName("tam_dung")
        self.ket_thuc = QtWidgets.QPushButton(self.groupBox_5)
        self.ket_thuc.setGeometry(QtCore.QRect(200, 420, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ket_thuc.setFont(font)
        self.ket_thuc.setObjectName("ket_thuc")
        self.display1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.display1.setGeometry(QtCore.QRect(360, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.display1.setFont(font)
        self.display1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.display1.setObjectName("display1")
        self.label_107 = QtWidgets.QLabel(self.centralwidget)
        self.label_107.setGeometry(QtCore.QRect(470, 40, 181, 41))
        self.label_107.setObjectName("label_107")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(410, 180, 181, 41))
        self.output.setFrameShape(QtWidgets.QFrame.Box)
        self.output.setAlignment(QtCore.Qt.AlignCenter)
        self.output.setObjectName("output")
        self.date = QtWidgets.QDateEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(360, 120, 111, 21))
        self.date.setObjectName("date")
        self.combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.combo_box.setGeometry(QtCore.QRect(510, 120, 86, 21))
        self.combo_box.setObjectName("combo_box")
        self.combo_box.addItem("a")
        self.combo_box.addItem("b")
        self.combo_box.addItem("c")
        self.combo_box.itemDelegate()
        self.checkBox1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox1.setGeometry(QtCore.QRect(640, 120, 141, 21))
        self.checkBox1.setObjectName("checkBox1")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(340, 250, 431, 201))
        self.groupBox_7.setObjectName("groupBox_7")
        self.display_vao = QtWidgets.QLabel(self.groupBox_7)
        self.display_vao.setGeometry(QtCore.QRect(10, 140, 131, 41))
        self.display_vao.setObjectName("display_vao")
        self.display_khong_khau_trang = QtWidgets.QLabel(self.groupBox_7)
        self.display_khong_khau_trang.setGeometry(QtCore.QRect(10, 90, 261, 41))
        self.display_khong_khau_trang.setObjectName("display_khong_khau_trang")
        self.label_109 = QtWidgets.QLabel(self.groupBox_7)
        self.label_109.setGeometry(QtCore.QRect(10, 40, 181, 41))
        self.label_109.setObjectName("label_109")
        self.display_khau_trang = QtWidgets.QLCDNumber(self.groupBox_7)
        self.display_khau_trang.setGeometry(QtCore.QRect(270, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.display_khau_trang.setFont(font)
        self.display_khau_trang.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.display_khau_trang.setFrameShadow(QtWidgets.QFrame.Plain)
        self.display_khau_trang.setObjectName("display_khau_trang")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox_7)
        self.lcdNumber_3.setGeometry(QtCore.QRect(270, 140, 91, 41))
        self.lcdNumber_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox_7)
        self.lcdNumber_4.setGeometry(QtCore.QRect(270, 90, 91, 41))
        self.lcdNumber_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # event
        self.bat_dau.clicked.connect(self.get_date)
        self.tam_dung.clicked.connect(self.insert_data)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def get_date(self):
        date = self.combo_box.currentText()
        if str(date) == "Ngày":
            self.display1.display(1)
            self.output.setText(str(1))
        elif str(date) == "Tháng":
            self.display1.display(2)
            self.output.setText(str(2))
        elif str(date) == "Năm":
            self.display1.display(3)
            self.output.setText(str(3))

    def insert_data(self):
        data = [
            {"camera_name": "camera1", "status": "working"},
            {"camera_name": "camera2", "status": "stopped"},
            {"camera_name": "camera3", "status": "working"},
            {"camera_name": "camera4", "status": "working"}
        ]

        row_count = (len(data))
        column_count = (len(data[0]))
        # self.table.setHorizontalHeaderLabels((list(data[0].keys())))
        for row in range(row_count):  # add items from array to QTableWidget
            for column in range(column_count):
                item = (list(data[row].values())[column])
                self.table.setItem(row, column, QtWidgets.QTableWidgetItem(item))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Trạng thái hoạt động"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TÊN"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TRẠNG THÁI"))
        __sortingEnabled = self.table.isSortingEnabled()
        self.table.setSortingEnabled(False)
        item = self.table.item(0, 0)
        item.setText(_translate("MainWindow", "T1 - Cửa chính"))
        item = self.table.item(0, 1)
        item.setText(_translate("MainWindow", "Đang họat động"))
        item = self.table.item(1, 0)
        item.setText(_translate("MainWindow", "T2 - Cầu thang"))
        item = self.table.item(1, 1)
        item.setText(_translate("MainWindow", "Dừng"))
        self.table.setSortingEnabled(__sortingEnabled)
        self.bat_dau.setText(_translate("MainWindow", "Bắt đầu"))
        self.tam_dung.setText(_translate("MainWindow", "Tạm dừng"))
        self.ket_thuc.setText(_translate("MainWindow", "Kết thúc"))
        self.label_107.setText(_translate("MainWindow", "Tổng số mang khẩu trang"))
        self.output.setText(_translate("MainWindow", "Output"))
        # self.combo_box.setItemText(0, _translate("MainWindow", "Ngày"))
        # self.combo_box.setItemText(1, _translate("MainWindow", "Tháng"))
        # self.combo_box.setItemText(2, _translate("MainWindow", "Năm"))
        self.checkBox1.setText(_translate("MainWindow", "Bật"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Kết quả tổng quát"))
        self.display_vao.setText(_translate("MainWindow", "Tổng số người vào:"))
        self.display_khong_khau_trang.setText(_translate("MainWindow", "Tổng số không mang khẩu trang(KT):"))
        self.label_109.setText(_translate("MainWindow", "Tổng số mang khẩu trang:"))


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        global w_height, w_width
        super().__init__()
        self.setupUi(self)
        self.setFixedSize(w_width, w_height)
        self.settings = QtCore.QSettings()
        restore(self.settings)

    def closeEvent(self, event):
        save(self.settings)
        super().closeEvent(event)


if __name__ == '__main__':
    print("(***)--- Running APP threading")
    import sys

    app = QtWidgets.QApplication(sys.argv)
    QtCore.QCoreApplication.setOrganizationName("Eyllanesc")
    QtCore.QCoreApplication.setOrganizationDomain("eyllanesc.com")
    QtCore.QCoreApplication.setApplicationName("MyApp")
    w = MainWindow()
    w.show()
    app.exec_()
