# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startbutton = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(700, 380, 141, 51))
        self.startbutton.setObjectName("startbutton")
        self.stopbutton = QtWidgets.QPushButton(self.centralwidget)
        self.stopbutton.setGeometry(QtCore.QRect(700, 440, 141, 51))
        self.stopbutton.setObjectName("stopbutton")
        self.status_start_button = QtWidgets.QLabel(self.centralwidget)
        self.status_start_button.setGeometry(QtCore.QRect(670, 160, 181, 20))
        self.status_start_button.setObjectName("status_start_button")
        self.alarm_option_label = QtWidgets.QLabel(self.centralwidget)
        self.alarm_option_label.setGeometry(QtCore.QRect(670, 20, 201, 20))
        self.alarm_option_label.setObjectName("alarm_option_label")
        self.input1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input1.setGeometry(QtCore.QRect(10, 530, 531, 25))
        self.input1.setObjectName("input1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(680, 50, 112, 23))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(680, 80, 112, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(680, 110, 151, 23))
        self.radioButton_3.setObjectName("radioButton_3")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(730, 200, 61, 26))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit_2.setGeometry(QtCore.QRect(830, 200, 61, 26))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.status_start_button_2 = QtWidgets.QLabel(self.centralwidget)
        self.status_start_button_2.setGeometry(QtCore.QRect(680, 200, 41, 20))
        self.status_start_button_2.setObjectName("status_start_button_2")
        self.status_start_button_3 = QtWidgets.QLabel(self.centralwidget)
        self.status_start_button_3.setGeometry(QtCore.QRect(800, 200, 41, 20))
        self.status_start_button_3.setObjectName("status_start_button_3")
        self.startbutton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton_2.setGeometry(QtCore.QRect(560, 530, 89, 25))
        self.startbutton_2.setObjectName("startbutton_2")
        self.status_start_button_4 = QtWidgets.QLabel(self.centralwidget)
        self.status_start_button_4.setGeometry(QtCore.QRect(10, 500, 51, 20))
        self.status_start_button_4.setObjectName("status_start_button_4")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(90, 500, 112, 23))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(220, 500, 112, 23))
        self.radioButton_5.setObjectName("radioButton_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 250, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCamera = QtWidgets.QAction(MainWindow)
        self.actionCamera.setObjectName("actionCamera")
        self.actionWebcam = QtWidgets.QAction(MainWindow)
        self.actionWebcam.setObjectName("actionWebcam")
        self.actionExport_data = QtWidgets.QAction(MainWindow)
        self.actionExport_data.setObjectName("actionExport_data")
        self.actionLight = QtWidgets.QAction(MainWindow)
        self.actionLight.setObjectName("actionLight")
        self.actionSound = QtWidgets.QAction(MainWindow)
        self.actionSound.setObjectName("actionSound")
        self.actionExport_Data = QtWidgets.QAction(MainWindow)
        self.actionExport_Data.setObjectName("actionExport_Data")
        self.menuMain.addAction(self.actionExport_Data)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startbutton.setText(_translate("MainWindow", "START"))
        self.stopbutton.setText(_translate("MainWindow", "STOP"))
        self.status_start_button.setText(_translate("MainWindow", "Working time"))
        self.alarm_option_label.setText(_translate("MainWindow", "Alarm Option"))
        self.label.setText(_translate("MainWindow", "Video"))
        self.radioButton.setText(_translate("MainWindow", "Light"))
        self.radioButton_2.setText(_translate("MainWindow", "Sound"))
        self.radioButton_3.setText(_translate("MainWindow", "Light and Sound"))
        self.status_start_button_2.setText(_translate("MainWindow", "From"))
        self.status_start_button_3.setText(_translate("MainWindow", "To"))
        self.startbutton_2.setText(_translate("MainWindow", "APPLY"))
        self.status_start_button_4.setText(_translate("MainWindow", "Source"))
        self.radioButton_4.setText(_translate("MainWindow", "IP Camera"))
        self.radioButton_5.setText(_translate("MainWindow", "Webcam"))
        self.label_2.setText(_translate("MainWindow", "No-face-mask"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.actionCamera.setText(_translate("MainWindow", "Camera"))
        self.actionWebcam.setText(_translate("MainWindow", "Webcam"))
        self.actionExport_data.setText(_translate("MainWindow", "Export data"))
        self.actionLight.setText(_translate("MainWindow", "Light"))
        self.actionSound.setText(_translate("MainWindow", "Sound"))
        self.actionExport_Data.setText(_translate("MainWindow", "Export Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

